### ISSUE TITLE
modals

### ISSUE THREAD

**Issue by bigtone1284** [SamMatthews9/JavaScript-Motion-Activated-Midi#37]
@SamMatthews9 @RossWittenberg  hey was looking over your code because I remember you guys using modals really well on your pj and wanted to use modals similarly.  

I read over modals.js and pretty much understand it (so a modal is just a div that rises above the rest of the body, huh?  cool).  

then I looked over header.js and saw that that's where you manage the click events and associated logic for your modals.  Was curious; do those click events get turned on when the page loads and did you have to do anything in app.js to get that to happen?  

Hope break is treating you pretty well.

**Comment by SamMatthews9** [comment]
Hey Tony,
In app.js we call the modalReady(); function, which is the first function in the modals.js file.  This function sets up the modals be generating the content for each one, and sets up the click event for each one.  The actual divs (for the click events) live on the application.html.erb.  These are empty divs, and the actual content gets generated in the modal.js file.  We used z-index to hide the divs underneath the primary page until one of the click events is fired.
